services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandbuilders
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - vendor:/app/vendor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - application
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: bb_mysql_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    user: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - application
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $DB_USERNAME -p$DB_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: bb-adminer
    ports:
      - 8080:8080
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
networks:
  application:
    driver: bridge
volumes:
  vendor:
